
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: digitalrig.azurecr.io/digitalrig/maven-app:latest
        imagePullPolicy: Always
        
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-svc
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
